services:

  pstocky:
    build: ./pstocky
    ports:
      - "8000:8000"
    environment:
      - REDIS_CONN=redis://redisdb:6379/2
      - DEBUG=True
    depends_on:
      - redisdb



  redisdb:
    image: redis:3.2




